name: "Auto-assign Issues"

on:
  issues:
    types:
      - opened
  workflow_dispatch:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Hello World!"

