name: Run Mocha Unit Tests

on:
  push:
    branches:
    - main
    - development
  pull_request:
  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

